### ISSUE TITLE
Public URL throws ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by LucasBednarek** [socketxp-com/home-assistant#2]
After resolving #1 HA add-on starts successfully, but public URL throws "ERR_CONNECTION_CLOSED". The same issue occurs when I am using `socketxp connect http://127.0.0.1:8123` after installing it directly on HA.

My config:

```
authtoken: "token"
tunnel_enabled: true
tunnels:
  - destination: 'http://127.0.0.1:8123'
    protocol: http
    custom_domain: ''
relay_enabled: false
relays:
  - destination: 'http://127.0.0.1:8123'
```

Are there any prerequisites on a firewall or Home Assistant level to get it to work?
